[en]
  languageName = "English"
  languageCode = "en"
  weight = 1
  title = "autonate"
  [en.params]
    tagline = "ğŸ‘‹ğŸ» Hi, Iâ€™m Nathan, a technical professional from the UK with an interest in AI, Automation, System Administration, Cloud Computing, and DevOps"